<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 11 Le facteur de Bayes | Initiation à l’approche bayésienne du traitement des données</title>
<meta name="author" content="Nicolas Stefaniak">
<meta name="description" content="Dans la partie consacrée à la vraisemblance, nous avons calculé la vraisemblance pour l’hypothèse selon laquelle le QI de cette assemblée ne se distinguait pas de celui de la moyenne de la...">
<meta name="generator" content="bookdown 0.43 with bs4_book()">
<meta property="og:title" content="Chapter 11 Le facteur de Bayes | Initiation à l’approche bayésienne du traitement des données">
<meta property="og:type" content="book">
<meta property="og:description" content="Dans la partie consacrée à la vraisemblance, nous avons calculé la vraisemblance pour l’hypothèse selon laquelle le QI de cette assemblée ne se distinguait pas de celui de la moyenne de la...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 11 Le facteur de Bayes | Initiation à l’approche bayésienne du traitement des données">
<meta name="twitter:description" content="Dans la partie consacrée à la vraisemblance, nous avons calculé la vraisemblance pour l’hypothèse selon laquelle le QI de cette assemblée ne se distinguait pas de celui de la moyenne de la...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.9.0/transition.js"></script><script src="libs/bs3compat-0.9.0/tabs.js"></script><script src="libs/bs3compat-0.9.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><link href="libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">
<script src="libs/tabwid-1.1.3/tabwid.js"></script><link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script><script src="libs/plotly-binding-4.11.0/plotly.js"></script><script src="libs/typedarray-0.1/typedarray.min.js"></script><link href="libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet">
<script src="libs/crosstalk-1.2.1/js/crosstalk.min.js"></script><link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script><link href="libs/panelset-0.3.0/panelset.css" rel="stylesheet">
<script src="libs/panelset-0.3.0/panelset.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
          margin-bottom: 0em;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Initiation à l’approche bayésienne du traitement des données</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html"></a></li>
<li><a class="" href="remerciements.html">Remerciements</a></li>
<li><a class="" href="%C3%A1-propos-de-cet-ouvrage..html"><span class="header-section-number">1</span> Á propos de cet ouvrage.</a></li>
<li><a class="" href="introduction.html"><span class="header-section-number">2</span> Introduction</a></li>
<li><a class="" href="le-th%C3%A9or%C3%A8me-de-bayes.html"><span class="header-section-number">3</span> Le théorème de Bayes</a></li>
<li><a class="" href="accumuler-les-informations..html"><span class="header-section-number">4</span> Accumuler les informations.</a></li>
<li><a class="" href="les-axiomes-des-probabilit%C3%A9s.html"><span class="header-section-number">5</span> Les axiomes des probabilités</a></li>
<li><a class="" href="quelques-rappels-sur-lapproche-de-neyman-pearson.html"><span class="header-section-number">6</span> Quelques rappels sur l’approche de Neyman-Pearson</a></li>
<li><a class="" href="les-probabilit%C3%A9s-objectif-ou-subjectif.html"><span class="header-section-number">7</span> Les probabilités : objectif ou subjectif</a></li>
<li><a class="" href="la-probabilit%C3%A9-a-priori.html"><span class="header-section-number">8</span> La probabilité a priori</a></li>
<li><a class="" href="la-vraisemblance.html"><span class="header-section-number">9</span> La vraisemblance</a></li>
<li><a class="" href="la-probabilit%C3%A9-a-posteriori.html"><span class="header-section-number">10</span> La probabilité a posteriori</a></li>
<li><a class="active" href="le-facteur-de-bayes.html"><span class="header-section-number">11</span> Le facteur de Bayes</a></li>
<li><a class="" href="comparaison-avec-lapproche-fr%C3%A9quentiste.html"><span class="header-section-number">12</span> Comparaison avec l’approche fréquentiste</a></li>
<li><a class="" href="exercices.html"><span class="header-section-number">13</span> Exercices</a></li>
<li><a class="" href="conclusions.html"><span class="header-section-number">14</span> Conclusions</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="le-facteur-de-bayes" class="section level1" number="11">
<h1>
<span class="header-section-number">11</span> Le facteur de Bayes<a class="anchor" aria-label="anchor" href="#le-facteur-de-bayes"><i class="fas fa-link"></i></a>
</h1>
<p>Dans la partie consacrée à la
<a href="la-vraisemblance.html#vraisemblance-et-variable-quantitative">vraisemblance</a>, nous avons
calculé la vraisemblance pour l’hypothèse selon laquelle le QI de cette
assemblée ne se distinguait pas de celui de la moyenne de la population
générale (l’hypothèse nulle) et pour l’hypothèse selon laquelle cette
assemblée avait un QI de 122<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content="&lt;p&gt;les formules exactes utilisées dans l’approche
bayésienne n’ont pas d’importance pour la compréhension, c’est pourquoi la
description porte la logique générale plutôt que sur l’exactitude mathématique.
Le point critique est de comprendre que la vraisemblance est la probabilité
d’observer les données pour une hypothèse donnée.&lt;/p&gt;"><sup>11</sup></a>. Nous avons vu que la
vraisemblance était très différente pour l’hypothèse où le QI moyen de
cette assemblée était de 100 et pour l’hypothèse où le QI moyen de
l’assemblée était de 122. On pourrait se demander à quel point
l’hypothèse selon laquelle “le QI moyen est à 122” est plus probable que
l’hypothèse selon laquelle “le QI moyen est de 100”. Si on pouvait
répondre à cette question, on pourrait alors savoir si nous disposons de
preuves tangibles en faveur d’une hypothèse par rapport à une autre.</p>
<p>Pour répondre à cette question, on peut simplement faire le rapport
entre les deux (voir l’équation <a href="le-facteur-de-bayes.html#eq:BF">(11.1)</a>). Ce rapport de vraisemblance
est ce qu’on apppelle le facteur de Bayes.</p>
<p><span class="math display" id="eq:BF">\[\begin{equation}
  \frac{P\left(H_1|D \right)}{P\left(H_0|D \right)} =
  \frac{P\left(H_1\right)}{P\left(H_0\right)}
  \times
  \frac{P\left(D|H_1 \right)}{P\left(D|H_0 \right)}
  \tag{11.1}
\end{equation}\]</span></p>
<p>où, pour rappel, P(H|D) est la probabilité d’une hypothèse étant donné
les données et P(D|H) est la probabilité des données étant donné une
hypothèse, c’est-à-dire la vraisemblance.</p>
<p>On peut formuler aussi les choses d’une autre manière :</p>
<p><span class="math display" id="eq:BF2">\[\begin{equation}
  \text{Cotes a posteriori} =\text{Cotes a priori} \times \text{rapport de vraisemblance}
  \tag{11.2}
\end{equation}\]</span></p>
<p>Rappelez-vous qu’on a déjà évoqué les cotes en faveur d’une hypothèse
par rapport à une autre, notamment quand vous avez dû parier sur le fait
que cette formation changerait votre manière de penser vos recherches. Pour avoir le rapport <em>a posteriori</em>, il faut donc multiplier votre rapport <em>a priori</em> par le rapport de vraisemblance.
Par ailleurs, nous avons déjà calculé la vraisemblance pour les deux
hypothèses. Nous pouvons donc examiner le rapport de vraisemblance :</p>
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">FB</span><span class="op">&lt;-</span><span class="va">vraisemblance122</span><span class="op">/</span><span class="va">vraisemblance100</span></span>
<span><span class="va">FB</span></span></code></pre></div>
<pre><code>## [1] 4691204879</code></pre>
<p>Dans le contexte bayésien, le rapport de vraisemblance est appelé le facteur de Bayes (B). Une
notation <span class="math inline">\(B_{01}\)</span> indique qu’on place la vraisemblance de l’hypothèse
nulle au numérateur et celle de l’hypothèse alternative au dénominateur.
Ainsi, une facteur de Bayes supérieur à 1 dans ce cas apporterait du
soutien en faveur de l’hypothèse nulle tandis qu’un facteur de Bayes
inférieur à 1 apporterait un soutien en faveur de l’hypothèse
alternative. La notation <span class="math inline">\(B_{01}\)</span> signifie que c’est la vraisemblance de
l’hypothèse alternative qui est au numérateur. L’interprétation est donc
l’inverse que celle de <span class="math inline">\(B_{01}\)</span>. Si B est proche de 1, alors
l’expérimentation manque de sensibilité, sans doute parce que vous
n’avez pas assez de participant·es. Remarquez ici que vous pouvez
distinguer les situations où votre expérimentation n’est pas assez
discriminante entre l’hypothèse nulle et l’hypothèse alternative des
situations où <strong>les preuves soutiennent l’hypothèse nulle</strong>. Ceci
représente une différence majeure par rapport à l’approche fréquentiste
où on ne peut que tolérer l’hypothèse nulle. En effet, dans le cadre de l’approche fréquentiste, il faut se rappeler que l’absence de preuve
n’est pas la preuve de l’absence <span class="citation">(<a href="references.html#ref-Caldwell2022">Caldwell, 2022</a>; <a href="references.html#ref-Lakens2017">Lakens, 2017</a>; voir néanmoins le packages TOSTER qui
permet de tester des hypothèses nulles en utilisant une approche
fréquentiste, <a href="references.html#ref-Lakens2018">Lakens et al., 2018</a>)</span>. Dans notre cas,
nous avons placé la vraisemblance au numérateur, cela signifie que
l’hypothèse d’un QI moyen à 122 est
4691204878.88566 fois plus probable que l’hypothèse
nulle. En d’autres termes, même avec une très faible probabilité
<em>a priori</em> en faveur de l’hypothèse alternative, ce rapport est tellement
énorme que la probabilité <em>a posteriori</em> serait proche de 1. La question
qui se pose est comment interpréter ces facteurs de Bayes dans des
situations moins claires ? Est-ce qu’un FB de 1.5 est suffisamment
élevé pour apporter du soutien à une hypothèse ?</p>
<p>Les bayésiens vous diraient que c’est à vous de décider, qu’ils se
refusent à proposer des heuristiques arbitraires telle que le fameux
<span class="math inline">\(p&lt;.05\)</span> pour déclarer qu’un effet est significatif. Néanmoins, certains
auteur <span class="citation">(par ex., <a href="references.html#ref-Wagenmakers2011">Wagenmakers et al., 2011</a>)</span> ont apporté des balises qui
permettent aux personnes qui s’initient aux statistiques bayésiennes de
se positionner. Ces balises ont été établies pour que, ce qui représente
des preuves en faveur de l’hypothèse alternative, corresponde plus ou
moins à un effet significatif si on avait utilisé une approche
fréquentiste pour traiter les données.</p>
<div class="tabwid">
<style>.cl-1c3b76e0{}.cl-1c328e2c{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-1c3604e4{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-1c361f1a{width:1.356in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1c361f24{width:4.264in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1c361f25{width:1.356in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1c361f26{width:4.264in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1c361f2e{width:1.356in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1c361f2f{width:4.264in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1c361f30{width:1.356in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1c361f31{width:4.264in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style>
<div class="inline-table"><table data-quarto-disable-processing="true" class="cl-1c3b76e0">
<caption style="display:table-caption;margin:0pt;text-align:center;border-bottom: 0.00pt solid transparent;border-top: 0.00pt solid transparent;border-left: 0.00pt solid transparent;border-right: 0.00pt solid transparent;padding-top:3pt;padding-bottom:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;">
<span id="tab:FBinter">Table 11.1: </span><span>Balise permettant d'interpréter les facteurs de Bayes quand la vraisemblance pour l'hypothèse nulle est au numérateur (B10)</span>
</caption>
<thead><tr style="overflow-wrap:break-word;">
<th class="cl-1c361f1a"><p class="cl-1c3604e4"><span class="cl-1c328e2c">FB10</span></p></th>
<th class="cl-1c361f24"><p class="cl-1c3604e4"><span class="cl-1c328e2c">interprétation</span></p></th>
</tr></thead>
<tbody>
<tr style="overflow-wrap:break-word;">
<td class="cl-1c361f25"><p class="cl-1c3604e4"><span class="cl-1c328e2c">&gt;100</span></p></td>
<td class="cl-1c361f26"><p class="cl-1c3604e4"><span class="cl-1c328e2c">Preuves extrêmes en faveur de l'hypothèse alternative</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-1c361f25"><p class="cl-1c3604e4"><span class="cl-1c328e2c">&gt;30 et &lt;100</span></p></td>
<td class="cl-1c361f26"><p class="cl-1c3604e4"><span class="cl-1c328e2c">Très fortes preuves en faveur de l'hypothèse alternative</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-1c361f25"><p class="cl-1c3604e4"><span class="cl-1c328e2c">&gt;10 et &lt;30</span></p></td>
<td class="cl-1c361f26"><p class="cl-1c3604e4"><span class="cl-1c328e2c">Fortes preuves en faveur de l'hypothèse alternative</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-1c361f25"><p class="cl-1c3604e4"><span class="cl-1c328e2c">&gt;3 et &lt;10</span></p></td>
<td class="cl-1c361f26"><p class="cl-1c3604e4"><span class="cl-1c328e2c">Preuves substantielles en faveur de l'hypothèse alternative</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-1c361f25"><p class="cl-1c3604e4"><span class="cl-1c328e2c">&gt;1 et &lt;3</span></p></td>
<td class="cl-1c361f26"><p class="cl-1c3604e4"><span class="cl-1c328e2c">Preuves anecdotiques en faveur de l'hypothèse alternative</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-1c361f2e"><p class="cl-1c3604e4"><span class="cl-1c328e2c">1</span></p></td>
<td class="cl-1c361f2f"><p class="cl-1c3604e4"><span class="cl-1c328e2c">Absence de preuve</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-1c361f25"><p class="cl-1c3604e4"><span class="cl-1c328e2c">&lt;1 et &gt;1/3</span></p></td>
<td class="cl-1c361f26"><p class="cl-1c3604e4"><span class="cl-1c328e2c">Preuves anecdotiques en faveur de l'hypothèse nulle</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-1c361f25"><p class="cl-1c3604e4"><span class="cl-1c328e2c">&lt;1/3 et &gt;1/10</span></p></td>
<td class="cl-1c361f26"><p class="cl-1c3604e4"><span class="cl-1c328e2c">Preuves substantielles en faveur de l'hypothèse nulle</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-1c361f25"><p class="cl-1c3604e4"><span class="cl-1c328e2c">&lt;1/10 et &gt;1/30</span></p></td>
<td class="cl-1c361f26"><p class="cl-1c3604e4"><span class="cl-1c328e2c">Fortes preuves en faveur de l'hypothèse nulle</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-1c361f25"><p class="cl-1c3604e4"><span class="cl-1c328e2c">&lt;1/30 et &gt;1/100</span></p></td>
<td class="cl-1c361f26"><p class="cl-1c3604e4"><span class="cl-1c328e2c">Très fortes preuves en faveur de l'hypothèse nulle</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-1c361f30"><p class="cl-1c3604e4"><span class="cl-1c328e2c">&lt;1/100</span></p></td>
<td class="cl-1c361f31"><p class="cl-1c3604e4"><span class="cl-1c328e2c">Preuves extrêmes en faveur de l'hypothèse nulle</span></p></td>
</tr>
</tbody>
</table></div>
</div>
<p>De ce qui vient d’être expliqué découlent deux propriétés
particulièrement intéressante. D’abord, l’utilisation des facteurs de
Bayes n’implique pas que deux scientifiques aient les mêmes cotes a
priori en faveur d’une hypothèse. Puisqu’un facteur de Bayes est un
rapport de vraisemblance et que ce rapport ne dépend pas (vraiment) des
cotes <em>a priori</em>, quiconque peut mettre à jour sa cote en faveur d’une
hypothèse en la multipliant par le facteur de Bayes. Le facteur de Bayes
permet d’ajuster les cotes de façon continue sans devoir rejeter ou
accepter une hypothèse. D’ailleurs, nous avons vu dans la tâche où il
vous était demandé de classer les théories qu’il peut y avoir une
certaine part d’incertitude pour certaines théories alors qu’on accorde plus de crédit à d’autres, même si on se laisse une petite place pour le
doute. Après tout, est-ce que le faillibilisme n’est pas une propriété
inhérente de la science <span class="citation">(<a href="references.html#ref-peirce1877fixation">Peirce, 1877</a>; <a href="references.html#ref-popper1963conjectures">K. Popper, 1963</a>)</span> ?
Dans l’approche bayésienne, les données viennent moduler nos croyances,
nos convictions, bref, le crédit que nous accordons aux théories.</p>
<p>Le second point est que cette modulation peut se faire en faveur de
l’hypothèse nulle. On peut avoir des preuves en faveur de l’hypothèse
nulle, et donc la tester. Dans la suite de cette section, nous allons
dans un premier temps présenter de manière plus rigoureuse la manière de
calculer les facteurs de Bayes avant d’illustrer ces propriétés en
reprenant une procédure assez similaire à celle que nous avons utilisée
pour illutrer certaines limites de l’approche de Neyman-Pearson
<span class="citation">(<a href="references.html#ref-Neyman1933">Neyman &amp; Pearson, 1933</a>)</span>.</p>
<p>Nous terminerons en évoquant comment on peut s’assurer que notre facteur
de Bayes n’a pas été influencé par le choix de la distribution a priori.</p>
<div id="un-peu-de-rigueur-mathématique" class="section level2" number="11.1">
<h2>
<span class="header-section-number">11.1</span> Un peu de rigueur mathématique<a class="anchor" aria-label="anchor" href="#un-peu-de-rigueur-math%C3%A9matique"><i class="fas fa-link"></i></a>
</h2>
<p>Si vous n’êtes pas sensibles à la précision mathématique mais que vous vous placez uniquement dans la perspective de l’utilisateur, cette section peut être omise. En revanche, si les imprécisions mathématiques (volontaires) que j’ai pu faire jusqu’à présent vous chagrine, cette section corrigera les manquements que je me suis permis jusqu’à présent (pour des raisons pédagogiques).</p>
<p>En effet, les calculs qui ont été réalisés jusqu’à présent pour obtenir les
facteurs de Bayes ont négligé la rigueur mathématique pour favoriser
l’aspect pédagogique. Ainsi, si on utilisait la fonction
<code>ttestBF</code> <span class="citation">(<a href="references.html#ref-Morey2024">Morey &amp; Rouder, 2024</a>)</span> qui permet de réaliser un <em>t</em> de
Student en utilisant l’approche bayésienne, nous aurions également des
preuves substantielles en faveur de l’hypothèse alternative mais la
valeur serait beaucoup moins élevée que celle que nous avons calculée.</p>
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://richarddmorey.github.io/BayesFactor/">BayesFactor</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">tBF.out</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/pkg/BayesFactor/man/ttestBF.html">ttestBF</a></span><span class="op">(</span><span class="va">QI</span>, <span class="co"># Les données </span></span>
<span>        mu <span class="op">=</span> <span class="fl">100</span>, <span class="co"># la norme pour fixer l'hypothèse nulle</span></span>
<span>        rscale <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">2</span><span class="op">)</span><span class="op">)</span> <span class="co"># La distribution a priori pour une distribution ultrawide (vu que la taille d'effet qu'on s'attend à avoir est grande)</span></span>
<span></span>
<span><span class="va">tBF.out</span></span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] Alt., r=1.414 : 1144439 ±0%
## 
## Against denominator:
##   Null, mu = 100 
## ---
## Bayes factor type: BFoneSample, JZS</code></pre>
<p>Pour obtenir cette valeur, il faut s’appuyer sur la formule exacte qui est fournie par Rouder et al.
<span class="citation">(<a href="references.html#ref-Rouder2009">2009</a>)</span> et décrite dans l’équation <a href="le-facteur-de-bayes.html#eq:Rouder">(11.3)</a></p>
<p><span class="math display" id="eq:Rouder">\[\begin{equation}
B_{10} = \frac{ \int_{0}^{\infty} \left(1+Ng\right)^{-1/2} \times  
\Bigg( 1+\frac{t^2}{(1+Ng)\times v}\Bigg)^{\left(v+1\right)/2} \times 2\pi^{-1/2} \times g^{-3/2} \times e^{-1/(2g) \times dg}}{\Bigg( 1+\frac{t^2}{v}\Bigg)^{(v+1)/2}}
  \tag{11.3}
\end{equation}\]</span></p>
<p>Dans cette équation, <em>t</em> représente la valeur du <em>t</em> de Student (selon
l’approche fréquentiste), N représente la taille de l’échantillon, v
représente les degrés de liberté (N-1) et g représente la densité de
probabilité sur la distribution Cauchy dont nous avons parlé
précédemment.</p>
<p>Nous pouvons à présent montrer comment la valeur est réellement calculée
dans le package <em>BayesFactor</em> <span class="citation">(<a href="references.html#ref-Morey2024">Morey &amp; Rouder, 2024</a>)</span>.</p>
<dl>
<dt>Nous allons commencer par préparer les informations les plus accessibles</dt>
<dd>
la valeur du <em>t</em> de Student selon l’approche fréquentiste. On peut
obtenir cette information grâce à la fonction <code>t.test</code>.
</dd>
</dl>
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># on commence par faire un t de Student fréquentiste</span></span>
<span><span class="co"># on extrait la valeur t </span></span>
<span><span class="va">tstat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">QI</span> , mu <span class="op">=</span> <span class="fl">100</span><span class="op">)</span><span class="op">$</span><span class="va">statistic</span></span>
<span><span class="va">tstat</span></span></code></pre></div>
<pre><code>##        t 
## 10.33488</code></pre>
<p>On récupère la taille de l’échantillon et nous établissons le
<code>rscale</code></p>
<div class="sourceCode" id="cb57"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># on récupère le nombre d'obervations (nécssaire notamment pour les ddl)</span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">QI</span><span class="op">)</span></span>
<span><span class="va">rscale</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">2</span><span class="op">)</span></span></code></pre></div>
<p>Dans l’équation, le dénominateur est la partie la plus simple à
comprendre. Il s’agit de la densité de probabilité sous hypothèse nulle.
Il s’agit pratiquement de ce que nous avons fait précédemment, avec la
nuance que nous allons utiliser une distribution <em>t</em> plutôt qu’une
distribution normale. Pour la distribution normale, la fonction était
<code>dnorm</code>. Pour la distribution <em>t</em>, la fonction est
<code>dt</code>.</p>
<div class="sourceCode" id="cb58"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># fonction de densité marginale sous H0</span></span>
<span><span class="co"># la fonction dt permet de calculer une densité de probabilité </span></span>
<span><span class="co"># pour une distribution t, comme dnorm le fait pour une distribution normale </span></span>
<span><span class="co"># On peut donc calculer la</span></span>
<span><span class="co"># densité sous H0 : p(D | H0)</span></span>
<span><span class="co"># ce sera le dénominateur </span></span>
<span><span class="va">denominator</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">dt</a></span><span class="op">(</span><span class="va">tstat</span>, df <span class="op">=</span> <span class="va">n</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">denominator</span></span></code></pre></div>
<pre><code>##                t 
## 0.00000001176713</code></pre>
<p>Il y a deux différences importantes entre le numérateur et le
dénominateur : la première est qu’on doit réaliser une intégrale. La
seconde est qu’il faut pondérer la vraisemblance conditionnelle,
c’est-à-dire la vraisemblance pour une multitude de cas de tailles
d’effets possibles, par la densité de probabilité de la distribution
Cauchy. Vous ne serez pas surpris·e d’apprendre qu’il existe une
fonction pour calculer la densité de probabilité sur une distribution
Cauchy qui s’appelle <code>dcauchy</code>. Dans l’équation <a href="le-facteur-de-bayes.html#eq:Rouder">(11.3)</a>, on remarque
aussi qu’une partie du numérateur correspond au dénominateur, qu’on doit
appliquer dans le cadre d’une intégrale. On suppose que la taille
d’effet <span class="math inline">\(\delta\)</span> suit une distribution Cauchy centrée en 0, dont la
largeur dépend du paramètre rscale. On va modéliser la distribution des
tailles d’effet possible en utilisant l’argument <code>ncp</code> avec
comme valeur <span class="math inline">\(\delta \times \sqrt{n}\)</span> pour calculer la vraisemblance
d’observer la statistique t. L’idée est de se demander quelle serait la
vraisemblance d’avoir cette valeur de <em>t</em> si la taille d’effet avait
comme valeur <span class="math inline">\(\delta\)</span> et que ce <span class="math inline">\(\delta\)</span> se distribuait en suivant une
distribution Cauchy avec le paramètre <code>rscale</code> que nous avons
choisi. Il va falloir faire l’intégrale<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content="&lt;p&gt;pour ceux et celles peu à l’aise avec les intégrales,
l’idée dans le cas présent est de calculer une surface qui n’est pas
simple à calculer puisque c’est une ditribution, il faut donc
découper cette distribution en une multitude de batonnets qui vont
se rapprocher chacune d’un rectangle. Le calcul de la surface d’un
rectangle étant facile à faire, il suffira d’additionner la surface
de cette multitude de rectangles&lt;/p&gt;"><sup>12</sup></a>, c’est-à-dire
envisager pratiquement tous les cas de figures possibles pour une taille
d’effet variant de -=<span class="math inline">\(\delta = -4\)</span> à <span class="math inline">\(\delta=4\)</span>, R requiert que la
fonction permettant de faire des intégrales <code>integrate</code> ait
comme argument principal la fonction pour laquelle on doit faire
l’intégrale. Nous allons donc dans un premier créer une fonction
<code>integrand</code> qui pourra être utilisée pour faire l’intégrale.</p>
<div class="sourceCode" id="cb60"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Il va falloir faire la même chose à présent pour H1</span></span>
<span><span class="co"># il faut calculer la densité p(D | H1)</span></span>
<span><span class="co"># nous allons devoir préciser le paramètre de non-centralité</span></span>
<span><span class="co"># c'est-a-dire notre prior </span></span>
<span><span class="co"># nous allons devoir faire l'intégrale pour les différentes valeurs possibles </span></span>
<span><span class="co"># cette intégrale a approximativement un incrément de 1/100 entre chaque valeur entre -4 et 4</span></span>
<span><span class="co"># le delta va être pondéré par la forme de la distribution Cauchy </span></span>
<span><span class="va">integrand</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">delta</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">dt</a></span><span class="op">(</span><span class="va">tstat</span>, </span>
<span>     df <span class="op">=</span> <span class="va">n</span> <span class="op">-</span> <span class="fl">1</span>, </span>
<span>     ncp <span class="op">=</span> <span class="va">delta</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span><span class="op">)</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/stats/Cauchy.html">dcauchy</a></span><span class="op">(</span><span class="va">delta</span>, scale <span class="op">=</span> <span class="va">rscale</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="co"># On peut faire l'intégrale numérique de : p(D | H1)</span></span>
<span><span class="va">numerator</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/integrate.html">integrate</a></span><span class="op">(</span><span class="va">integrand</span>, lower <span class="op">=</span> <span class="op">-</span><span class="cn">Inf</span>, upper <span class="op">=</span> <span class="cn">Inf</span><span class="op">)</span><span class="op">$</span><span class="va">value</span></span>
<span></span>
<span></span>
<span></span>
<span><span class="co"># On  peut obtenir le facteur de Bayes</span></span>
<span><span class="va">bf_manual</span> <span class="op">&lt;-</span> <span class="va">numerator</span> <span class="op">/</span> <span class="va">denominator</span></span>
<span><span class="va">bf_manual</span></span></code></pre></div>
<pre><code>##       t 
## 1144439</code></pre>
</div>
<div id="ajuster-nos-probabilités" class="section level2" number="11.2">
<h2>
<span class="header-section-number">11.2</span> Ajuster nos probabilités<a class="anchor" aria-label="anchor" href="#ajuster-nos-probabilit%C3%A9s"><i class="fas fa-link"></i></a>
</h2>
<p>Dans la section d’introduction aux facteurs de Bayes, nous avons évoqué le fait que le facteur de Bayes permettait d’ajuster de manière continue notre probabilité.</p>
<p>Un outil intéressant pour comprendre cette idée et pour identifier la direction que prend le facteur de Bayes est de faire des analyses séquentielles. L’idée est qu’on va estimer le facteur de bayes pour un échantillon qui va d’un petit échantillon à la taille complète de l’échantillon dont on dispose, en choisissant de manière aléatoire les observations tant qu’on n’a pas atteint une taille d’échantillon N égale à la taille de l’échantillon pour lequel on a recueilli les données.</p>
<p>Cette analyse permet de voir si le facteur de Bayes est dépendant de quelques observations où s’il s’agit d’une tendance générale qui se dessine.</p>
<p>Nou pouvons reprendre notre exemple sur le QI pour illustrer cette idée. Pour pouvoir faire ces analyses séquentielles, nous devons utiliser le package <em>changeofevidence</em> <span class="citation">(<a href="references.html#ref-Moritz2025">Dechamps, 2025</a>)</span> qui intègre cette possibilité, ce qui à ma connaissance n’est pas le cas avec le package <em>BayesFactor</em> <span class="citation">(<a href="references.html#ref-Morey2024">Morey &amp; Rouder, 2024</a>)</span>. Dans le package <em>changeofevidence</em>, on obtient la facteur de Bayes pour un test <em>t</em> avec la fonction <code>bfttest</code>. Il suffit ensuite de faire une représentation graphique de la sortie de résultats (voir Figure <a href="le-facteur-de-bayes.html#fig:sequentialBF">11.1</a>)</p>
<div class="sourceCode" id="cb62"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">changeofevidence</span><span class="op">)</span></span>
<span></span>
<span><span class="va">bf.exp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/changeofevidence/man/bfttest.html">bfttest</a></span><span class="op">(</span><span class="va">QI</span>, mu <span class="op">=</span> <span class="fl">100</span>, alternative <span class="op">=</span> <span class="st">"two.sided"</span>, prior.loc <span class="op">=</span> <span class="fl">0</span>, prior.r <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">2</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   |                                                                              |                                                                      |   0%  |                                                                              |=====                                                                 |   7%  |                                                                              |=========                                                             |  13%  |                                                                              |==============                                                        |  20%  |                                                                              |===================                                                   |  27%  |                                                                              |=======================                                               |  33%  |                                                                              |============================                                          |  40%  |                                                                              |=================================                                     |  47%  |                                                                              |=====================================                                 |  53%  |                                                                              |==========================================                            |  60%  |                                                                              |===============================================                       |  67%  |                                                                              |===================================================                   |  73%  |                                                                              |========================================================              |  80%  |                                                                              |=============================================================         |  87%  |                                                                              |=================================================================     |  93%  |                                                                              |======================================================================| 100%</code></pre>
<div class="sourceCode" id="cb64"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">bf.exp</span><span class="op">)</span></span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:sequentialBF"></span>
<img src="bookdown-demo_files/figure-html/sequentialBF-1.png" alt="Représentation graphique des facteurs de Bayes séquentiels" width="672"><p class="caption">
Figure 11.1: Représentation graphique des facteurs de Bayes séquentiels
</p>
</div>
<p>Pour comprendre l’intérêt de ce type d’analyse, il suffit de rajouter une observation qui serait aberrante, par exemple un QI à 40 et voir comment le facteur de Bayes évolue (voir Figure <a href="le-facteur-de-bayes.html#fig:sequentialBF2">11.2</a>).</p>
<div class="sourceCode" id="cb65"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">QI2</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">QI</span>, <span class="fl">40</span><span class="op">)</span></span>
<span><span class="va">bf.exp2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/changeofevidence/man/bfttest.html">bfttest</a></span><span class="op">(</span><span class="va">QI2</span>, mu <span class="op">=</span> <span class="fl">100</span>, alternative <span class="op">=</span> <span class="st">"two.sided"</span>, </span>
<span>                   prior.loc <span class="op">=</span> <span class="fl">0</span>, prior.r <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">2</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   |                                                                              |                                                                      |   0%  |                                                                              |====                                                                  |   6%  |                                                                              |=========                                                             |  12%  |                                                                              |=============                                                         |  19%  |                                                                              |==================                                                    |  25%  |                                                                              |======================                                                |  31%  |                                                                              |==========================                                            |  38%  |                                                                              |===============================                                       |  44%  |                                                                              |===================================                                   |  50%  |                                                                              |=======================================                               |  56%  |                                                                              |============================================                          |  62%  |                                                                              |================================================                      |  69%  |                                                                              |====================================================                  |  75%  |                                                                              |=========================================================             |  81%  |                                                                              |=============================================================         |  88%  |                                                                              |==================================================================    |  94%  |                                                                              |======================================================================| 100%</code></pre>
<div class="sourceCode" id="cb67"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">bf.exp2</span><span class="op">)</span></span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:sequentialBF2"></span>
<img src="bookdown-demo_files/figure-html/sequentialBF2-1.png" alt="Représentation graphique des facteurs de Bayes séquentiels" width="672"><p class="caption">
Figure 11.2: Représentation graphique des facteurs de Bayes séquentiels
</p>
</div>
<p>On se rend compte ici que la valeur aberrante va drastiquement influencer la valeur du facteur du Bayes (à la baisse). Ainsi, on peut savoir quelles sont les observations qui sont influentes et si le facteur de Bayes a été modifié par quelques observations uniquement.</p>
<p>Cette manière d’analyser les données vous permet donc de vous assurer que votre facteur de Bayes ne dépend pas que de quelques observations qui feraient pencher la vraisemblance d’un côté ou de l’autre.</p>
</div>
<div id="tester-une-hypothèse-nulle" class="section level2" number="11.3">
<h2>
<span class="header-section-number">11.3</span> Tester une hypothèse nulle<a class="anchor" aria-label="anchor" href="#tester-une-hypoth%C3%A8se-nulle"><i class="fas fa-link"></i></a>
</h2>
<p>Une des raisons principales en faveur de l’utilisation de l’approche bayésienn est que le facteur de Bayes permet de tester une hypothèse nulle car la vraisemblance peut être plus élevée pour l’hypothèse nulle que pour l’hypothèse alternative, ce qui n’était pas le cas pour l’approche de Neyman-Pearson <span class="citation">(<a href="references.html#ref-Neyman1933">Neyman &amp; Pearson, 1933</a>)</span> car, non seulement, il y avait le risque de faux positifs à 5%, mais surtout parce que, dès lors que la taille d’échantillon augmente, on aura un effet significatif même pour de petits effets.</p>
<p>Nous allons examiner ces deux cas de figures sous l’angle bayésiens en utilisant les mêmes paramètres que ceux utilisés précédemment. La seule différence est que nous allons travailler avec 20 000 échantillons plutôt que 200 000 car les temps de calculs sont considérablement allongés pour l’approche bayésienne.</p>
<div class="sourceCode" id="cb68"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># le fait de mettre une graine assure une reproductibilité des résultats </span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1234</span><span class="op">)</span> </span>
<span><span class="co"># on va créer une fonction qui compare deux moyennes qui sont strictement égales lorsque la condition vaut 0 et</span></span>
<span><span class="co"># dont les moyennes se différencient de 0,2 écart-type (d = 0.2) quand la condition vaut 1</span></span>
<span><span class="co"># La fonction renvoie la probabilité du test t </span></span>
<span></span>
<span><span class="va">F2</span><span class="op">&lt;-</span><span class="kw">function</span><span class="op">(</span><span class="va">cond</span> <span class="op">=</span> <span class="fl">0</span><span class="op">)</span><span class="op">{</span> </span>
<span>  <span class="kw">if</span><span class="op">(</span><span class="va">cond</span><span class="op">==</span><span class="fl">0</span><span class="op">)</span><span class="op">{</span></span>
<span>  <span class="co"># on fait une comparaison de deux populations dont les moyennes sont strictement égales </span></span>
<span>  <span class="va">t.out</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/pkg/BayesFactor/man/ttestBF.html">ttestBF</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">20</span>, <span class="co"># taille de l'échantillon 1</span></span>
<span>                      mean <span class="op">=</span> <span class="fl">0</span>, <span class="co"># moyenne du groupe 1</span></span>
<span>                      sd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>, <span class="co"># écart-type de l'échantillon 1</span></span>
<span>                <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">20</span>, <span class="co"># taille de l'échantillon 2</span></span>
<span>                      mean <span class="op">=</span> <span class="fl">0</span>,<span class="co"># moyenne du groupe 2</span></span>
<span>                      sd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">)</span><span class="co"># écart-type de l'échantillon 2</span></span>
<span>  <span class="op">}</span><span class="kw">else</span><span class="op">{</span> </span>
<span>                        <span class="va">t.out</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/pkg/BayesFactor/man/ttestBF.html">ttestBF</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">20</span>, <span class="co"># taille de l'échantillon 1</span></span>
<span>                                            mean <span class="op">=</span> <span class="fl">0</span>, <span class="co"># moyenne du groupe 1</span></span>
<span>                                            sd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>, <span class="co"># écart-type de l'échantillon 1</span></span>
<span>                                      <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">20</span>, <span class="co"># taille de l'échantillon 2</span></span>
<span>                                            mean <span class="op">=</span> <span class="fl">0.2</span>,<span class="co"># moyenne du groupe 2</span></span>
<span>                                            sd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">)</span> <span class="co"># écart-type de l'échantillon 2</span></span>
<span>                      <span class="op">}</span></span>
<span>  </span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/BayesFactor/man/extractBF-methods.html">extractBF</a></span><span class="op">(</span><span class="va">t.out</span><span class="op">)</span><span class="op">$</span><span class="va">bf</span><span class="op">)</span> <span class="co"># renvoie le FB </span></span>
<span>  </span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="co"># on crée des données (200 000) : pour créer de manière aléatoire nos conditions. Elles sont au nombre de 200 000</span></span>
<span><span class="co"># ici l'échantillonnage se fait de manière équiprobable avec approximativement autant de situations pour la</span></span>
<span><span class="co"># condition différence qu'absence de différence </span></span>
<span><span class="va">df</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>condition <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fl">0</span><span class="op">:</span><span class="fl">1</span>, </span>
<span>                                  <span class="fl">20000</span>, <span class="co">#20000, </span></span>
<span>                                  replace<span class="op">=</span><span class="cn">T</span> <span class="op">)</span><span class="op">)</span> </span>
<span></span>
<span><span class="co"># on applique la fonction F pour chacune des lignes du jeu de données (variable condition)</span></span>
<span><span class="va">df</span><span class="op">$</span><span class="va">BF</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">df</span>, <span class="fl">1</span>, <span class="va">F2</span><span class="op">)</span></span>
<span></span>
<span></span>
<span><span class="va">df</span><span class="op">$</span><span class="va">sig1</span><span class="op">&lt;-</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else</a></span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">condition</span><span class="op">==</span><span class="fl">1</span> <span class="op">&amp;</span> <span class="va">df</span><span class="op">$</span><span class="va">BF</span><span class="op">&gt;</span><span class="fl">3</span> <span class="op">|</span> </span>
<span>                   <span class="va">df</span><span class="op">$</span><span class="va">condition</span><span class="op">==</span><span class="fl">0</span> <span class="op">&amp;</span> <span class="va">df</span><span class="op">$</span><span class="va">BF</span><span class="op">&lt;</span><span class="fl">1</span><span class="op">/</span><span class="fl">3</span>, <span class="st">"correct"</span>,</span>
<span>                 <span class="fu"><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else</a></span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">condition</span><span class="op">==</span><span class="fl">1</span> <span class="op">&amp;</span> <span class="va">df</span><span class="op">$</span><span class="va">BF</span><span class="op">&lt;</span><span class="fl">1</span><span class="op">/</span><span class="fl">3</span> <span class="op">|</span>  </span>
<span>                           <span class="va">df</span><span class="op">$</span><span class="va">condition</span><span class="op">==</span><span class="fl">0</span> <span class="op">&amp;</span> <span class="va">df</span><span class="op">$</span><span class="va">BF</span><span class="op">&gt;</span><span class="fl">3</span>, <span class="st">"incorrect"</span>,</span>
<span>                 <span class="st">"manque de sensibilité"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span></span>
<span><span class="va">T1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">condition</span>, <span class="va">df</span><span class="op">$</span><span class="va">sig1</span><span class="op">)</span></span>
<span><span class="va">T1</span>  </span></code></pre></div>
<pre><code>##    
##     correct incorrect manque de sensibilité
##   0    3416       193                  6411
##   1     428      2847                  6705</code></pre>
<p>On constate que, avec ces paramètres, l’analyse va indiquer la plupart du temps (dans 66% des situations) que l’expérience manquent de sensibilité pour prendre une décision. Par ailleurs, l’hypothèse nulle est rejetée à tort avec un taux d’erreur inférieur au 5% des tests d’hypothèse nulle ( 1.93 % des situations). Enfin, le taux d’erreur est plus élevée pour la situation où la taille d’effet est de 0.2 et que le facteur de Bayes nous indique que nous avons des preuves en faveur de l’hypothèse nulle ( 28.53 %). Si ce taux d’erreur est loin d’être négligeable, il faut noter que ce taux d’erreur reste considérablement plus faible que celui observé avec l’approche fréquentiste (pour rappel, on tolérait l’hypothèse nulle dans 91% des situations). Par ailleurs, le fait d’observer plus de situations où une différence alternative sera considérée comme une hypothèse nulle est un phénomène tout à fait cohérent avec l’approche bayésienne.</p>
<p>En effet, il faut garder à l’esprit que l’absence totale d’effet n’existe jamais réellement mais que ce sont des approximations d’invariance <span class="citation">(<a href="references.html#ref-Cohen1994">Cohen, 1994</a>)</span>. Si une absence totale de différence est quasiment impossible, le fait est que certaines tailles d’effet sont tellement négligeables qu’on ne peut pas décemment avancer qu’elles représentent quelque chose qui ait du sens pour le domaine de recherche exploré. Il faut comprendre ici, que presque paradoxalement, cette même taille d’effet pourrait être d’un intérêt substantiel dans un autre domaine. Il faut donc pouvoir mettre aussi en évidence cet effet minimal. Par exemple, en psychologie, on considérerait sans intérêt un effet qui ne toucherait par exemple qu’une personne sur 10000 mais il s’agit de la fréquence avec laquelle un jeune vacciné contre la covid développe une myocardite. Il s’agit donc d’un risque identifié pour le <a href="https://www.assurance-maladie.ameli.fr/etudes-et-donnees/2022-vaccin-arn-messager-covid-19-myocardite-pericardite">vaccin de la covid</a> chez les jeunes et que ce risque est effectivement considéré comme un effet indésirable potentiel du vaccin contre la covid.</p>
<p>La question qui se pose donc est de savoir si le facteur de Bayes fournit la décision appropriée dans ce genre de situations, à savoir un facteur de Bayes supérieur à 3 à la condition d’avoir un très grand échantillon tout en restant en-dessous de 1/3 pour les échantillons de petites et moyennes tailles. Pour illustrer cette question, nous allons faire une simulation similaire (les changements ont surtout vocation à réduire les temps de calcul) à celle relative sur une différence de 0.1 point sur un test de QI entre deux populations.</p>
<div class="sourceCode" id="cb70"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://richarddmorey.github.io/BayesFactor/">BayesFactor</a></span><span class="op">)</span></span>
<span><span class="va">F1</span><span class="op">&lt;-</span><span class="kw">function</span><span class="op">(</span><span class="va">n</span><span class="op">)</span><span class="op">{</span></span>
<span>  <span class="va">t.out</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/pkg/BayesFactor/man/ttestBF.html">ttestBF</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n</span>, <span class="fl">100</span>,<span class="fl">15</span><span class="op">)</span>, </span>
<span>                <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n</span>, <span class="fl">100.1</span>,<span class="fl">15</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/BayesFactor/man/extractBF-methods.html">extractBF</a></span><span class="op">(</span><span class="va">t.out</span><span class="op">)</span><span class="op">$</span><span class="va">bf</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="va">df</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">2</span><span class="op">^</span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">20</span><span class="op">)</span>, <span class="fl">100</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">df</span><span class="op">$</span><span class="va">bf</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">df</span>, <span class="fl">1</span>, <span class="va">F1</span><span class="op">)</span></span>
<span></span>
<span><span class="va">df</span><span class="op">$</span><span class="va">Decision</span><span class="op">&lt;-</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else</a></span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">bf</span><span class="op">&gt;</span><span class="fl">3</span>, <span class="st">"Preuves en faveur de l'alternative"</span>,</span>
<span>                    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else</a></span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">bf</span><span class="op">&lt;</span><span class="fl">1</span><span class="op">/</span><span class="fl">3</span>, <span class="st">"Preuves en faveur de l'hypothèse nulle"</span>,</span>
<span>                    <span class="st">"Manque de sensibilité"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">df2</span><span class="op">&lt;-</span><span class="va">df</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">n</span>, <span class="va">Decision</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>Nombre<span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">df2</span>, <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">n</span>, y<span class="op">=</span><span class="va">Nombre</span>, colour <span class="op">=</span><span class="va">Decision</span><span class="op">)</span><span class="op">)</span><span class="op">+</span><span class="fu">geom_line</span><span class="op">(</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu">ylab</span><span class="op">(</span><span class="st">"Nombre de décision précise (sur 100)"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="bookdown-demo_files/figure-html/simulQIdataBF-1.png" width="672"></div>
<p>On se rend compte qu’avec la même simulation que celle que nous avons utilisée précédemment, le facteur de Bayes pour des tailles d’échantillon modérée, voire grande, va favoriser l’hypothèse nulle mais, avec des échantillons énormes, le facteur de Bayes va pencher en faveur d’un effet réel. Remarquez la différence de comportement par rapport à l’approche fréquentiste où le nombre d’effets significatifs augmentait de manière proportionnelle à la taille de l’échantillon.</p>
<p>Qu’est-ce que cela signifie : si on s’intéresse à des effets raisonnablement importants, des tailles d’échantillons de quelques dizaines, voire de quelques centaines de participants vont favoriser l’hypothèse nulle si la taille d’effet observée est effectivement ridicule. En revanche, si on s’intéresse à de toutes petites tailles d’effet, on sait qu’il faudra un échantillon conséquent pour le mettre en évidence (sans doute plusieurs milliers de données) et, dans ce cas, le FB sera en mesure de le mettre en évidence.</p>
<p>Pour Rouder et al. <span class="citation">(<a href="references.html#ref-Rouder2009">2009</a>)</span>, ce comportement est idéal : avec les petites tailles d’échantillon, on n’a pas assez d’informations pour distinguer une absence totale d’effet d’un effet extrêmement petit, ce qui permettra au chercheur et à la chercheuse d’accumuler des preuves en faveur de l’hypothèse nulle, et avec de très larges échantillons, le facteur de Bayes permet de découvrir de très petits effets. Pour le formuler autrement : le facteur de Bayes favorise un modèle plus parcimonieux, à savoir l’absence de différence, à moins que l’échantillon soit si large que même des petits effets ne sont pas compatibles avec l’hypothèse nulle.</p>
<p>Dans la section <a href="#quand-un-effet-n%C3%A9gligeable-est-significatif">sur les effets négligeables</a>, nous avions donné l’exemple d’une étude publiée où une corrélation de 0.08 était significative parce que l’échantillon était tout de même conséquent. Si on essaie de reproduire au mieux les données, qu’observe-t-on avec une approche bayésienne ?</p>
<div class="sourceCode" id="cb71"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://richarddmorey.github.io/BayesFactor/">BayesFactor</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://www.stats.ox.ac.uk/pub/MASS4/">MASS</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">46</span><span class="op">)</span></span>
<span><span class="co"># create the variance covariance matrix</span></span>
<span><span class="va">sigma</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">0.08</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.08</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co"># create the mean vector</span></span>
<span><span class="va">mu</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">76.51</span>, <span class="fl">51.45</span> <span class="op">)</span> </span>
<span><span class="co"># generate the multivariate normal distribution</span></span>
<span><span class="va">df</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/MASS/man/mvrnorm.html">mvrnorm</a></span><span class="op">(</span>n<span class="op">=</span><span class="fl">526</span>, mu<span class="op">=</span><span class="va">mu</span>, Sigma<span class="op">=</span><span class="va">sigma</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/cor.test.html">cor.test</a></span><span class="op">(</span><span class="va">df</span><span class="op">[</span>,<span class="fl">1</span><span class="op">]</span>, <span class="va">df</span><span class="op">[</span>,<span class="fl">2</span><span class="op">]</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
##  Pearson's product-moment correlation
## 
## data:  df[, 1] and df[, 2]
## t = 1.9706, df = 524, p-value = 0.04929
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.0002779501 0.1700172554
## sample estimates:
##        cor 
## 0.08576994</code></pre>
<div class="sourceCode" id="cb73"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">corrBF</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/pkg/BayesFactor/man/correlationBF.html">correlationBF</a></span><span class="op">(</span></span>
<span>y<span class="op">=</span> <span class="va">df</span><span class="op">[</span>,<span class="fl">1</span><span class="op">]</span>,</span>
<span>x<span class="op">=</span><span class="va">df</span><span class="op">[</span>,<span class="fl">2</span><span class="op">]</span>,</span>
<span>rscale <span class="op">=</span> <span class="st">"ultrawide"</span></span>
<span><span class="op">)</span></span>
<span><span class="va">corrBF</span></span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] Alt., r=1 : 0.3752612 ±0%
## 
## Against denominator:
##   Null, rho = 0 
## ---
## Bayes factor type: BFcorrelation, Jeffreys-beta*</code></pre>
<p>On voit ici qu’avec un facteur de Bayes de 0.375 on a quasiment un rapport de 1/3, donc des preuves en faveur de l’hypothèse nulle. Ces données sont beaucoup plus cohérentes pour interpréter une validité divergente.</p>
</div>
<div id="rôle-de-la-priori-sur-le-bayes-factor" class="section level2" number="11.4">
<h2>
<span class="header-section-number">11.4</span> Rôle de l’a priori sur le Bayes factor<a class="anchor" aria-label="anchor" href="#r%C3%B4le-de-la-priori-sur-le-bayes-factor"><i class="fas fa-link"></i></a>
</h2>
<p>Nous avons évoqué le fait que certaines personnes pouvaient être mal à l’aise avec l’idée que les résultats puissent dépendre de notre opinion plutôt que des faits objectifs.</p>
<p>Une manière simple de répondre à ce problème est de mener un analyse robuste. Concrètement, celle-ci consiste à examiner la valeur de facteur de Bayes pour différentes hypothèses <em>a priori</em> et s’assurer que le choix que vous avez fait n’influence pas de manière drastique vos résultats.</p>
<p>Le package <em>BayesFactor</em> <span class="citation">(<a href="references.html#ref-Morey2024">Morey &amp; Rouder, 2024</a>)</span> ne fournit pas de fonction permettant d’obtenir directement l’analyse robuste. Cependant, cela ne représente pas quelque chose de très difficile à faire. Le code annoté explique étape par étape la procédure à suivre.</p>
<div class="sourceCode" id="cb75"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># on commencer par établir la liste de priors que nous souhaitons tester</span></span>
<span><span class="co"># ici c'est une séquence qui va de 0.05 à 2, avec un accent particulier </span></span>
<span><span class="co"># sur les priors prédéfinis dans le package BayesFactor (0.5,0.707, 1,1.41)</span></span>
<span><span class="va">rs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span>from <span class="op">=</span> <span class="fl">.05</span>, to <span class="op">=</span><span class="fl">2</span>, by <span class="op">=</span> <span class="fl">0.05</span><span class="op">)</span>, <span class="fl">0.5</span>, <span class="fl">0.707</span>, <span class="fl">1</span>, <span class="fl">1.41</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># on veut pouvoir les calculer tous en même temps. </span></span>
<span><span class="co"># pour cela, on va utiliser la fonction sapply qui va </span></span>
<span><span class="co"># calculer le Bayes Factor pour tous les priors qu'on va lui donner (stockés dans rs)</span></span>
<span><span class="va">bfs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span><span class="op">(</span><span class="va">rs</span>, </span>
<span>              <span class="kw">function</span><span class="op">(</span><span class="va">r</span><span class="op">)</span> <span class="op">{</span> <span class="co"># on crée un fonction spécifiquement pour notre propos</span></span>
<span>  <span class="co"># on utilise exactement la même fonction que celle qu'on utilise pour un seul BF</span></span>
<span>  <span class="co"># mais au lieu de donner une valeur au rscale, on lui donne l'argument r</span></span>
<span>  <span class="co"># qui seront fournis par tous les rs              </span></span>
<span>  <span class="va">bf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/BayesFactor/man/ttestBF.html">ttestBF</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">QI</span>, mu <span class="op">=</span> <span class="fl">100</span>, rscale <span class="op">=</span> <span class="va">r</span><span class="op">)</span></span>
<span>  <span class="co"># on extrait les facteurs de Bayes</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/BayesFactor/man/extractBF-methods.html">extractBF</a></span><span class="op">(</span><span class="va">bf</span><span class="op">)</span><span class="op">$</span><span class="va">bf</span></span>
<span><span class="op">}</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># on crée un data.frame pour faire le graphique </span></span>
<span><span class="va">robust</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">rs</span>, <span class="va">bfs</span><span class="op">)</span> </span>
<span><span class="co"># on réalise le graphique </span></span>
<span></span>
<span><span class="co"># note les Bayes Factor sont sur une échelle qui permet de les représenter </span></span>
<span><span class="co">#en valeur </span></span>
<span><span class="co">#brute. Il peut être utile de faire une transformation logarithmique lorque </span></span>
<span><span class="co"># leur valeur est très élevée. </span></span>
<span></span>
<span><span class="co"># on fait la ligne qui touche tous les points</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">robust</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">rs</span>, y<span class="op">=</span><span class="va">bfs</span><span class="op">)</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span><span class="op">+</span> </span>
<span>  <span class="co"># on donne le titre à l'axe des x</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span><span class="op">(</span><span class="st">"Choix de la distribution a priori"</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="co"># on donne le titre à l'axe des y</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span><span class="op">(</span><span class="st">"Valeur du facteur de Bayes"</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="co"># on met en valeur les points des priors prédéfinis dans BayesFactor</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>data<span class="op">=</span><span class="va">robust</span><span class="op">[</span><span class="fl">41</span><span class="op">:</span><span class="fl">44</span>,<span class="op">]</span>, colour<span class="op">=</span><span class="st">"blue"</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="co"># On indique sur le graphique à quel prior chaque point correspond </span></span>
<span>  <span class="co"># en faisant un petit décalage afin d'éviter une superposition avec le point</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/annotate.html">annotate</a></span><span class="op">(</span><span class="st">"text"</span>, label <span class="op">=</span> <span class="va">robust</span><span class="op">$</span><span class="va">rs</span><span class="op">[</span><span class="fl">41</span><span class="op">:</span><span class="fl">44</span><span class="op">]</span>, </span>
<span>           x <span class="op">=</span> <span class="va">robust</span><span class="op">$</span><span class="va">rs</span><span class="op">[</span><span class="fl">41</span><span class="op">:</span><span class="fl">44</span><span class="op">]</span>,</span>
<span>           y <span class="op">=</span> <span class="va">robust</span><span class="op">$</span><span class="va">bfs</span><span class="op">[</span><span class="fl">41</span><span class="op">:</span><span class="fl">44</span><span class="op">]</span><span class="op">+</span><span class="fl">1</span>, colour <span class="op">=</span><span class="st">"blue"</span>, check_overlap <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:robust"></span>
<img src="bookdown-demo_files/figure-html/robust-1.png" alt="Graphique représentant les facteurs de Bayes calculés pour différents prior. Cette analyse est connue sous le nom d'analyse de robustesse." width="672"><p class="caption">
Figure 11.3: Graphique représentant les facteurs de Bayes calculés pour différents prior. Cette analyse est connue sous le nom d’analyse de robustesse.
</p>
</div>
<p>Dans ce graphique, on observe que, peu importe la distribution a priori choisie parmi les priord par défaut du package <em>BayesFactor</em> <span class="citation">(<a href="references.html#ref-Morey2024">Morey &amp; Rouder, 2024</a>)</span>, on dispose de preuves substantielles en faveur de l’existence d’une différence.</p>
<p>Si le code ci-dessus est directement adaptable en fonction des situations, dans le package <em>changeofevidence</em> <span class="citation">(<a href="references.html#ref-Moritz2025">Dechamps, 2025</a>)</span>, Moritz a développé des fonctions qui permettaient de le faire soit pour un test <em>t</em> ou pour une corrélation.</p>
<p>Comme nous avions déjà utilisé ce package précédemment, on peut réutiliser l’objet créé et le passer directement à la fonction <code>bfRobustness</code>.</p>
<div class="sourceCode" id="cb76"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">bf.robust</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/changeofevidence/man/bfRobustness.html">bfRobustness</a></span><span class="op">(</span><span class="va">bf.exp2</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Highest BF = 102.73 with prior: Cauchy(0.85, 0.05)</code></pre>
<div class="sourceCode" id="cb78"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">bf.robust</span><span class="op">)</span></span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:robust2"></span>
<img src="bookdown-demo_files/figure-html/robust2-1.png" alt="Analyses de robustesse avec le package changeofevidence" width="672"><p class="caption">
Figure 11.4: Analyses de robustesse avec le package changeofevidence
</p>
</div>
<p>Les réultats ne sont pas identique à l’analyse précédente car la fonction permet d’utiliser deux paramètres pour préciser la distribution <em>a priori</em> : la variance du prior, comme dans le package <em>BayesFactor</em> mais également la localisation de la taille d’effet, ce qui n’est pas le cas dans le package <em>BayesFactor</em>. La bande représente la zone dans laquelle les BayesFactor peut se situer en fonction de la combinaison des deux paramètres.
Pour reproduire le même graphique que celui qui a été obtenu précédemment, on peut préciser que <code>prior.loc</code> est égal à 0, comme dans le package <em>BayesFactor</em>.</p>
<div class="sourceCode" id="cb79"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">bf.robust</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/changeofevidence/man/bfRobustness.html">bfRobustness</a></span><span class="op">(</span><span class="va">bf.exp2</span>, prior.loc<span class="op">=</span><span class="fl">0</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Highest BF = 16.27 with prior: Cauchy(0, 0.7)</code></pre>
<div class="sourceCode" id="cb81"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">bf.robust</span><span class="op">)</span></span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:robust3"></span>
<img src="bookdown-demo_files/figure-html/robust3-1.png" alt="Analyses de robustesse avec le package changeofevidence pour un prior de localisation fixé à 0." width="672"><p class="caption">
Figure 11.5: Analyses de robustesse avec le package changeofevidence pour un prior de localisation fixé à 0.
</p>
</div>
</div>
</div>

  <div class="chapter-nav">
<div class="prev"><a href="la-probabilit%C3%A9-a-posteriori.html"><span class="header-section-number">10</span> La probabilité a posteriori</a></div>
<div class="next"><a href="comparaison-avec-lapproche-fr%C3%A9quentiste.html"><span class="header-section-number">12</span> Comparaison avec l’approche fréquentiste</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#le-facteur-de-bayes"><span class="header-section-number">11</span> Le facteur de Bayes</a></li>
<li><a class="nav-link" href="#un-peu-de-rigueur-math%C3%A9matique"><span class="header-section-number">11.1</span> Un peu de rigueur mathématique</a></li>
<li><a class="nav-link" href="#ajuster-nos-probabilit%C3%A9s"><span class="header-section-number">11.2</span> Ajuster nos probabilités</a></li>
<li><a class="nav-link" href="#tester-une-hypoth%C3%A8se-nulle"><span class="header-section-number">11.3</span> Tester une hypothèse nulle</a></li>
<li><a class="nav-link" href="#r%C3%B4le-de-la-priori-sur-le-bayes-factor"><span class="header-section-number">11.4</span> Rôle de l’a priori sur le Bayes factor</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Initiation à l’approche bayésienne du traitement des données</strong>" was written by Nicolas Stefaniak. It was last built on 2025-07-09.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
